# ── Configuración principal (override en cada perfil) ───────────
spring.application.name=testing-lab

spring.datasource.url=jdbc:postgresql://localhost:5432/lab
spring.datasource.username=lab
spring.datasource.password=lab

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

payment.service.url=http://payment-service:8080
